#!/usr/bin/env python3
"""Generate the Homebrew formula for Tollgate.

A Homebrew formula for a Python CLI vendors every dependency as a `resource`
block with a pinned URL and SHA-256, so `brew install` needs no network access
to PyPI's resolver and no pip on the user's machine. Maintaining those by hand
is a chore and getting one hash wrong breaks the install, so this regenerates
the whole file from the dependency set that pip actually resolves.

    python packaging/generate_formula.py 0.3.0 > Formula/tollgate.rb

Run it after publishing to PyPI — it reads the real sdist hashes from there, so
the release has to exist first. `--allow-missing` emits a placeholder for the
main package so you can see the shape before publishing.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
import urllib.error
import urllib.request
from pathlib import Path

PACKAGE = "tollgate-proxy"
PYPROJECT = Path(__file__).resolve().parent.parent / "pyproject.toml"

#: Packages whose sdist needs a compiler Homebrew would have to install first.
#: Nothing in the current tree does — Tollgate deliberately depends only on
#: pure-Python packages so `brew install` never pulls a build toolchain — but a
#: future dependency might, and a silently broken install is worse than a noisy
#: formula.
BUILD_DEPS = {"pydantic_core": "rust", "pydantic-core": "rust", "cryptography": "rust"}


def requirements() -> list[str]:
    """Read the runtime dependencies from pyproject, so this can't drift."""
    import tomllib

    with open(PYPROJECT, "rb") as f:
        return tomllib.load(f)["project"]["dependencies"]


def pypi(name: str, version: str | None = None) -> dict:
    url = f"https://pypi.org/pypi/{name}/json" if version is None else (
        f"https://pypi.org/pypi/{name}/{version}/json"
    )
    with urllib.request.urlopen(url, timeout=30) as response:
        return json.load(response)


def sdist(name: str, version: str) -> tuple[str, str]:
    """The source tarball URL and hash. Homebrew builds from source."""
    data = pypi(name, version)
    for entry in data["urls"]:
        if entry["packagetype"] == "sdist":
            return entry["url"], entry["digests"]["sha256"]
    raise SystemExit(f"{name} {version} publishes no sdist; Homebrew needs one")


def resolve() -> list[tuple[str, str]]:
    """Ask pip to resolve the tree, so the formula matches a real install."""
    with tempfile.TemporaryDirectory() as tmp:
        report = Path(tmp) / "report.json"
        subprocess.run(
            [
                sys.executable, "-m", "pip", "install",
                "--dry-run", "--ignore-installed", "--quiet",
                "--report", str(report), *requirements(),
            ],
            check=True,
        )
        data = json.loads(report.read_text())
    return sorted(
        (item["metadata"]["name"], item["metadata"]["version"])
        for item in data["install"]
    )


def render(version: str, allow_missing: bool) -> str:
    try:
        main_url, main_sha = sdist(PACKAGE, version)
    except (urllib.error.HTTPError, urllib.error.URLError):
        if not allow_missing:
            raise SystemExit(
                f"{PACKAGE} {version} is not on PyPI yet. Publish first, or pass "
                "--allow-missing to see the shape."
            )
        main_url = f"https://files.pythonhosted.org/packages/source/t/{PACKAGE}/{PACKAGE}-{version}.tar.gz"
        main_sha = "PUBLISH_TO_PYPI_THEN_REGENERATE"

    resources = resolve()
    build_deps = sorted({BUILD_DEPS[n] for n, _ in resources if n in BUILD_DEPS})

    lines = [
        "# Generated by packaging/generate_formula.py — do not edit by hand.",
        "class Tollgate < Formula",
        '  include Language::Python::Virtualenv',
        "",
        '  desc "Local capture proxy for LLM API traffic, with cost attribution"',
        '  homepage "https://github.com/sat-wik/tollgate"',
        f'  url "{main_url}"',
        f'  sha256 "{main_sha}"',
        '  license "MIT"',
        "",
        '  depends_on "python@3.13"',
    ]
    for dep in build_deps:
        lines.append(f'  depends_on "{dep}" => :build')
    lines.append("")

    for name, ver in resources:
        url, digest = sdist(name, ver)
        lines += [
            f'  resource "{name}" do',
            f'    url "{url}"',
            f'    sha256 "{digest}"',
            "  end",
            "",
        ]

    lines += [
        "  def install",
        "    virtualenv_install_with_resources",
        "  end",
        "",
        "  test do",
        "    # Proves the entry point works and the deps actually imported.",
        '    assert_match "tollgate", shell_output("#{bin}/tollgate --help")',
        '    assert_match "no capture log", shell_output(',
        '      "#{bin}/tollgate report --logs #{testpath}/none.jsonl 2>&1", 1',
        "    )",
        "  end",
        "end",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("version", help="the tollgate-proxy version to package")
    parser.add_argument(
        "--allow-missing",
        action="store_true",
        help="emit a placeholder if the version isn't on PyPI yet",
    )
    args = parser.parse_args()
    sys.stdout.write(render(args.version, args.allow_missing))


if __name__ == "__main__":
    main()
